version: "3.8"

services:
  backend:
    image: flashcasset/backend:latest
    container_name: flash-backend
    environment:
      - PORT=7861
      - CARDS_JSON_PATH=/data/cards/cards.json
    volumes:
      # Host deck folder -> container
      - /Users/ruihe/mnt/flashcards:/data/cards
    ports:
      - "7861:7861"
    restart: unless-stopped

  frontend:
    image: flashcasset/frontend:latest
    container_name: flash-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
